MyBlogSite.Web/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyBlogSite.Web.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class DashboardController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

MyBlogSite.Web/Areas/Admin/Controllers/EducationController.cs
using Data;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace MyBlogSite.Web.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class EducationController : Controller
	{
		private readonly ApplicationDbContext _db;

		public EducationController(ApplicationDbContext db)
		{
			_db = db;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult GetAllEducation()
		{
			return Json(new {data=_db.educations.Where(e => e.IsActive == true && e.IsDeleted == false).OrderByDescending(e => e.endDate).ToList() });
		}
		[HttpPost]
        public IActionResult EditEducation(Education education)
        {
			Education e = _db.educations.Find(education.Id);
            return Json(e);
        }
        [HttpPost]
        public IActionResult UpdateEducation(Education education)
        {
			Education e = _db.educations.Find(education.Id);
			e.description=education.description;	
			e.endDate=education.endDate;
			e.startDate=education.startDate;
			e.name=education.name;
			
			_db.educations.Update(e);
			_db.SaveChanges();
            return Json(education);
        }

		[HttpPost]
        public IActionResult AddEducation(Education education)
        {
            _db.educations.Add(education);
			_db.SaveChanges();
            return Json(education);
        }

		[HttpPost]
        public IActionResult DeleteEducation(Education education)
        {
            Education e = _db.educations.Find(education.Id);
            e.DateModified = DateTime.Now;
            e.IsDeleted = true;
            _db.educations.Update(e);
            _db.SaveChanges();
            return Json(e);
        }

    }
}

MyBlogSite.Web/Areas/Admin/Controllers/ExperienceController.cs
using Data;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace MyBlogSite.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
	public class ExperienceController : Controller
	{
		private readonly ApplicationDbContext _db;

        public ExperienceController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
		{
			return View();
		}
        public IActionResult GetAllExperience(Guid id)
        {
            return Json(_db.experiences.Where(e => e.IsActive == true && e.IsDeleted == false).OrderByDescending(e => e.EndDate).ToList() );
        }
        [HttpPost]
        public IActionResult UpdateExperience(Experience experience)
        {
           Experience e=_db.experiences.Find(experience.Id);
            if (e == null)
            {
                return View("Böyle bir Kayıt bulunamamaktadır");

            }
            e.Id= experience.Id;
            e.Name= experience.Name;
            e.EndDate= experience.EndDate;  
            e.StartDate= experience.StartDate;
            e.Description= experience.Description;
            e.ExperienceCity= experience.ExperienceCity;
            e.DateModified=DateTime.Now;
            _db.experiences.Update(e);
            _db.SaveChanges();
            return Json(experience);    
        }

        public IActionResult AddExperience(List<Experience> experiences)
        {
            _db.experiences.AddRange(experiences);
            _db.SaveChanges();

            return Json("Başarılı");
        } 
        public IActionResult DeleteExperience(Experience experience)
        {
            Experience e=_db.experiences.Find(experience.Id);
            e.DateModified = DateTime.Now;
            e.IsDeleted = true;
            _db.experiences.Update(e);
            _db.SaveChanges();
            return Json(e);
        }



    }
}

MyBlogSite.Web/Areas/Admin/Controllers/ImageController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyBlogSite.Web.Areas.Admin.Controllers
{
    public class ImageController : Controller
    {
        [Area("Admin")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

MyBlogSite.Web/Controllers/HomeController.cs
using Models;
using Microsoft.AspNetCore.Mvc;
using Data;
using Microsoft.EntityFrameworkCore;

namespace MyBlogSite.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _db;

        public HomeController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
            
        }

        public IActionResult GetProfile()
        {
              Profile profile = _db.profiles.Include(e=>e.Experiences).Include(i => i.Image).Where(i => i.IsDeleted == false && i.IsActive == true && i.Image.ImageType == "ProfilFoto").FirstOrDefault();

              profile.Experiences.AddRange(_db.experiences.Where(e=>e.IsActive==true && e.IsDeleted==false).OrderByDescending(e => e.EndDate).ToList());


			return Json(profile);
        }



		public IActionResult GetAllExperience()
		{
			return Json(_db.experiences.Where(e=>e.IsActive==true && e.IsDeleted==false).OrderByDescending(e=>e.EndDate).ToList());
		}

		public IActionResult GetAllEducation()
		{
			return Json(_db.educations.Where(e => e.IsActive == true && e.IsDeleted == false).OrderByDescending(e => e.endDate).ToList());
		}

	}
}

MyBlogSite.Web/Areas/Admin/Views/Dashboard/Index.cshtml
@{


}
@*<style>
    #photo {
        display: flex;
        align-items: center;
        justify-content: center;
        position: absolute;
        margin-bottom:50px;
        padding-bottom:50px;
        top: 0;
        left: 50%;
        right: 0;
    }
</style>*@

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <div style="width:170px;height:170px;position:relative;display:flex; justify-content:center;left:40%; " class="mb-3 row ">
                    <img src="~/img/apple-touch-icon.png" />
                </div>


                <div class="mb-3 row">
                    <label for="example-text-input" class="col-md-2 col-form-label">Ad Soyad</label>
                    <div class="col-md-10">
                        <input class="form-control" type="text" value="Artisanal kale" id="example-text-input">
                    </div>
                </div>
                <div class="mb-3 row">
                    <label for="example-search-input" class="col-md-2 col-form-label">İş</label>
                    <div class="col-md-10">
                        <input class="form-control" type="search" value="How do I shoot web" id="example-search-input">
                    </div>
                </div>

                <div class="mb-3 row">
                    <label for="example-search-input" class="col-md-2 col-form-label">Son Çalışılan İş</label>
                    <div class="col-md-10">
                        <input class="form-control" type="search" value="How do I shoot web" id="example-search-input">
                    </div>
                </div>

                <div class="mb-3 row">
                    <label for="example-search-input" class="col-md-2 col-form-label">Şehir</label>
                    <div class="col-md-10">
                        <input class="form-control" type="search" value="How do I shoot web" id="example-search-input">
                    </div>
                </div>


                <div class="mb-3 row">
                    <label for="example-search-input" class="col-md-2 col-form-label">Milliyet</label>
                    <div class="col-md-10">
                        <input class="form-control" type="search" value="How do I shoot web" id="example-search-input">
                    </div>
                </div>


                <div class="mb-3 row">
                    <label for="example-search-input" class="col-md-2 col-form-label">Teknoloji</label>
                    <div class="col-md-10">
                        <input class="form-control" type="search" value="How do I shoot web" id="example-search-input">
                    </div>
                </div>

                <div class="mb-3 row">
                    <label class="col-md-2 col-form-label">Medeni Haliniz</label>
                    <div class="col-md-10">
                        <select class="form-select">
                            <option>Seçiniz</option>
                            <option>Evli </option>
                            <option>Bekar</option>
                        </select>
                    </div>
                </div>

                <div class="mb-3 row">
                    <label for="example-email-input" class="col-md-2 col-form-label">Email Adresi</label>
                    <div class="col-md-10">
                        <input class="form-control" type="email" value="bootstrap@example.com" id="example-email-input">
                    </div>
                </div>

                <div class="mb-3 row">
                    <label for="example-tel-input" class="col-md-2 col-form-label">Telefon  </label>
                    <div class="col-md-10">
                        <input class="form-control" type="tel" value="1-(555)-555-5555" id="example-tel-input">
                    </div>
                </div>



                <div class="mb-3 row">
                    <label for="example-date-input" class="col-md-2 col-form-label">Doğum Tarihi</label>
                    <div class="col-md-10">
                        <input class="form-control" type="date" value="2019-08-19" id="example-date-input">
                    </div>
                </div>


                <div class="mb-3 row">
                    <label for="example-search-input" class="col-md-2 col-form-label">Hakkımda Kısaca</label>
                    <div class="col-md-10">
                        <input class="form-control" type="search" value="How do I shoot web" id="example-search-input">
                    </div>
                </div>


                <div class="mb-3 row">
                    <label for="example-search-input" class="col-md-2 col-form-label">Hakkkımda Geniş</label>
                    <div class="col-md-10">
                        <textarea class="form-control" name="" value="How do I shoot web" id="" rows="3"></textarea>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- end col -->
</div>

MyBlogSite.Web/Areas/Admin/Views/Education/Index.cshtml
@{

}
@section css{

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.css">
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <button id="btnEducationAdd"  class="btn btn-success waves-effect waves-light" type="button">Eğitimlerinizi Eklemek İçin Tıklayınız</button>
                <hr>
                <h4 class="card-title">Eğitim Listesi</h4>
                

                <table id="table" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                    <thead>
                        <tr>
                            <th>Eğitim Kurumu</th>
                            <th>Açıklama</th>
                            <th>Başlangıç Tarihi</th>
                            <th>Bitiş Tarihi</th>
                            <th>ProfileId </th>
                            <th>İşlemler</th>
                        </tr>
                    </thead>


                    <tbody>
                       
                    </tbody>
                </table>
            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->


<div id="modalAdd" class="modal fade bs-example-modal-xl" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myExtraLargeModalLabel">Eğitimi Ekle</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">

                                <form id="form" enctype="multipart/form-data">
                                    <div data-repeater-list="group-a">
                                        <div data-repeater-item class="row form">
                                            <div class="mb-3 col-sm-2">
                                                <label class="form-label" for="name">Eğitim Kurumu</label>
                                                <input type="text" id="name" name="untyped-input" class="form-control" placeholder="" />
                                            </div>

                                            <div class="mb-3 col-sm-2">
                                                <label class="form-label" for="startDate">Başlangıç Tarihi</label>
                                                <input type="text" id="startDate" name="startDate" class="form-control" placeholder="" />
                                            </div>

                                            <div class="mb-3 col-sm-2">
                                                <label class="form-label" for="endDate">Bitiş Tarihi</label>
                                                <input type="text" id="endDate" name="endDate" class="form-control" placeholder="" />
                                            </div>

                                            <div class="mb-3 col-lg-4">
                                                <label class="form-label" for="description">Açıklama</label>
                                                <textarea name="description" id="description" class="form-control" placeholder=""></textarea>
                                            </div>


                                            <div class="col-sm-2 align-self-center">
                                                <div class="d-grid">
                                                    <input id="btnAddEducation"  data-repeater-delete type="button" class="btn btn-primary" value="Eğitim Ekle" />
                                                </div>
                                            </div>


                                        </div>
                                        <input id="profileId" type="hidden" class="btn btn-primary" value="" />

                                    </div>



                                </form>

                            </div>

                        </div>
                    </div>

                </div>

            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>


<div id="modal" class="modal fade bs-example-modal-xl" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myExtraLargeModalLabel">Eğitimi Düzenle</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                               
                                <form id="form" enctype="multipart/form-data">
                                    <div data-repeater-list="group-a">
                                        <div data-repeater-item class="row form">
                                            <div class="mb-3 col-sm-2">
                                                <label class="form-label" for="name">Eğitim Kurumu</label>
                                                <input type="text" id="name" name="untyped-input" class="form-control" placeholder="" />
                                            </div>

                                            <div class="mb-3 col-sm-2">
                                                <label class="form-label" for="startDate">Başlangıç Tarihi</label>
                                                <input type="text" id="startDate" name="startDate" class="form-control" placeholder="" />
                                            </div>

                                            <div class="mb-3 col-sm-2">
                                                <label class="form-label" for="endDate">Bitiş Tarihi</label>
                                                <input type="text" id="endDate" name="endDate" class="form-control" placeholder="" />
                                            </div>
                                           
                                              <div class="mb-3 col-lg-4">
                                                <label class="form-label" for="description">Açıklama</label>
                                                <textarea name="description" id="description" class="form-control" placeholder=""></textarea>
                                            </div>


                                            <div class="col-sm-2 align-self-center">
                                                <div class="d-grid">
                                                    <input id="btnSaveEducation" onclick="updateEducation()" data-repeater-delete type="button" class="btn btn-primary" value=" Kaydet" />
                                                </div>
                                            </div>


                                        </div>
                                        <input id="profileId" type="hidden" class="btn btn-primary" value="" />

                                    </div>
                                 
                                 

                                </form>

                            </div>

                        </div>
                    </div>

                </div>

            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

@section Scripts{
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>

<script type="text/javascript">
        var dataTable;
    $(document).ready(function (){
       
         dataTable=$("#table").DataTable({
                ajax: "@Url.Action("GetAllEducation","Education")",
                columns: [
                    { data: 'name' },
                    { data: 'description' },
                    { data: 'startDate', render: function (data) { return new Date(data).toLocaleDateString('tr-TR')}},
                    { data: 'endDate', render: function (data) { return new Date(data).toLocaleDateString('tr-TR')} },
                    { data: 'profileId' },
                    {
                        data: 'id', render: function (data) {

                            return `<a onclick="editEducation('${data}')"  class="btn btn-outline-success btn-sm edit" title="Düzenle">
                                    <i class="uil-comment-alt-edit"></i>
                                                       <a onclick="deleteEducation('${data}')"  class="btn btn-outline-dark btn-sm edit" title="Sil">
                                                       <i class="uil-trash-alt"></i>
                                            `

                        }

                    }]
            });

           

          
   
    });

        function deleteEducation(id) {
            Swal.fire({
                title: 'Silmek İstediğinizden Emin Misiniz',

                showCancelButton: true,
                confirmButtonText: 'Evet',

            }).then((result) => {

                if (result.isConfirmed) {

                    var veri = {
                        id: id
                    }
                    $.ajax({
                        type: "POST",
                        url: "@Url.Action("DeleteEducation","Education")",
                        data: veri,
                        success: function (data) {
                          dataTable.ajax.reload();
                        }
                    });


                    Swal.fire('Silme İşlemi Başarılı!', 'Başarılı')
                }
            })
        }








        function editEducation(id){
            $("#modal").modal("show");
            var veri={
                id:id
            }
            $.ajax({
                type:"POST",
                url: "@Url.Action("EditEducation","Education")",
                data:veri,
                success:function(res){
                    $("#name").val(res.name);
                    $("#description").val(res.description);
                    $("#startDate").val(new Date(res.startDate).toLocaleDateString());
                    $("#endDate").val(new Date(res.endDate).toLocaleDateString());
                    $("#profileId").val(res.id);

                }
            
            });



    }
        function updateEducation(){
        var veri={
                id: $("#profileId").val(),
                name:$("#name").val(),
                description:$("#description").val(),
                startDate:$("#startDate").val(),
                endDate: $("#endDate").val()

        }
        $.ajax({
            type:"Post",
            data:veri,
            url:"@Url.Action("UpdateEducation","Education")",
            success:function(data){

               dataTable.ajax.reload();
               $("#modal").modal("hide");
                    $("#btnSaveEducation").off();
            }


        });
    }

        $("#btnEducationAdd").click(function () {
            var columnProfileId=$("#table tr td:first-child").next().next().next().next().html();
            $("#modalAdd").modal("show");
            $("#btnAddEducation").val("Deneyim Ekle");

            $("#btnAddEducation").click(function(){

                var veri = {
                    profileId: columnProfileId,
                    name: $("#name").val(),
                    description: $("#description").val(),
                    startDate: $("#startDate").val(),
                    endDate: $("#endDate").val()

                }
            
            $.ajax({
                    type: "POST",
                    url: "@Url.Action("AddEducation","Education")",
                    data: veri,
                    success: function (res) {
                        $("#name").val("");
                        $("#description").val("");
                        $("#startDate").val("");
                        $("#endDate").val("");
                        $("#profileId").val("");
                        $("#btnAddEducation").off();
                        $("#modalAdd").modal("hide");
                        dataTable.ajax.reload();

                    }
            
            
            });
            
            });

            
        });


       
</script>



}

MyBlogSite.Web/Areas/Admin/Views/Image/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <button id="btnAddImage" class="btn btn-success waves-effect waves-light" type="button">Fotoğraf Ekleyin</button>
                <hr>
                <h4 class="card-title">Fotoğraflar</h4>


                <table id="table" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                    <thead>
                        <tr>
                            <th>Fotoğraf</th>
                            <th>Fotoğraf Tipi</th>
                          
                        </tr>
                    </thead>


                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->

<div id="modal" class="modal fade bs-example-modal-xl" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
              
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body ">
              
               

            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

@section Scripts{

<script type="text/javascript">

    $("#btnAddImage").click(function(){
    $("#modal").modal("show");


    });

</script>


}

MyBlogSite.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
	<!-- Basic -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Blog Site</title>

	<meta name="keywords" content="WebSite Template" />
	<meta name="description" content="Blog Site">
	<meta name="author" content="okler.net">

	<!-- Favicon -->
	<link rel="shortcut icon" href="~/img/favicon.ico" type="image/x-icon" />
	<link rel="apple-touch-icon" href="~/img/apple-touch-icon.png">

	<!-- Mobile Metas -->
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">

	<!-- Web Fonts  -->
	<link id="googleFonts" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800&display=swap" rel="stylesheet" type="text/css">

	<!-- Vendor CSS -->
	<link rel="stylesheet" href="~/vendor/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="~/vendor/fontawesome-free/css/all.min.css">
	<link rel="stylesheet" href="~/vendor/animate/animate.compat.css">
	<link rel="stylesheet" href="~/vendor/simple-line-icons/css/simple-line-icons.min.css">
	<link rel="stylesheet" href="~/vendor/owl.carousel/assets/owl.carousel.min.css">
	<link rel="stylesheet" href="~/vendor/owl.carousel/assets/owl.theme.default.min.css">
	<link rel="stylesheet" href="~/vendor/magnific-popup/magnific-popup.min.css">

	<!-- Theme CSS -->
	<link rel="stylesheet" href="~/css/theme.css">
	<link rel="stylesheet" href="~/css/theme-elements.css">
	<link rel="stylesheet" href="~/css/theme-blog.css">
	<link rel="stylesheet" href="~/css/theme-shop.css">

	<!-- Demo CSS -->
	<link rel="stylesheet" href="~/css/demos/demo-resume.css">

	<!-- Skin CSS -->
	<link id="skinCSS" rel="stylesheet" href="~/css/skins/skin-resume-red.css">

	<!-- Theme Custom CSS -->
	<link rel="stylesheet" href="~/css/custom.css">

	<!-- Head Libs -->
	<script src="~/vendor/modernizr/modernizr.min.js"></script>

</head>
<body data-plugin-scroll-spy data-plugin-options="{'target': '.wrapper-spy'}">
	<div class="body">
	<header id="header" class="header-floating-icons" data-plugin-options="{'stickyEnabled': false, 'stickyEnableOnBoxed': false, 'stickyEnableOnMobile': false, 'stickyStartAt': 0, 'stickySetTop': '60px', 'stickyChangeLogo': false}">
		<div class="header-body bg-transparent">
			<div class="header-container container">
				<div class="header-row">
					<div class="header-column">
						<div class="header-row">
							<div class="header-nav pt-1">
								<div class="header-nav-main">
									<nav class="wrapper-spy collapse">
										<ul class="nav" id="mainNav">
											<li>
												<a data-hash href="#about-me" class="nav-link text-color-dark bg-color-primary">
													<i class="icon-home icons"></i>
													<span class="custom-tooltip text-color-dark">About Me</span>
												</a>
											</li>
											<li>
												<a data-hash href="#experience" class="nav-link text-color-dark bg-color-primary">
													<i class="icon-eye icons"></i>
													<span class="custom-tooltip text-color-dark">Experience</span>
												</a>
											</li>
											<li>
												<a data-hash href="#education" class="nav-link text-color-dark bg-color-primary">
													<i class="icon-briefcase icons"></i>
													<span class="custom-tooltip text-color-dark">Education</span>
												</a>
											</li>
											<li>
												<a data-hash href="#skills" class="nav-link text-color-dark bg-color-primary">
													<i class="icon-graduation icons"></i>
													<span class="custom-tooltip text-color-dark">Skills</span>
												</a>
											</li>
											<li>
												<a data-hash href="#portfolio" class="nav-link text-color-dark bg-color-primary">
													<i class="icon-diamond icons"></i>
													<span class="custom-tooltip text-color-dark">Portfolio</span>
												</a>
											</li>
											<li>
												<a data-hash data-hash-offset="0" data-hash-offset-lg="100" href="#recommendations" class="nav-link text-color-dark bg-color-primary">
													<i class="icon-pencil icons"></i>
													<span class="custom-tooltip text-color-dark">Recommendations</span>
												</a>
											</li>
											<li>
												<a data-hash href="#blog" class="nav-link text-color-dark bg-color-primary">
													<i class="icon-bubbles icons"></i>
													<span class="custom-tooltip text-color-dark">Blog</span>
												</a>
											</li>
											<li>
												<a data-hash href="#say-hello" class="nav-link text-color-dark bg-color-primary">
													<i class="icon-envelope-open icons"></i>
													<span class="custom-tooltip text-color-dark">Say Hello</span>
												</a>
											</li>
										</ul>
									</nav>
								</div>
								<button class="btn header-btn-collapse-nav text-color-light border-radius-0" data-bs-toggle="collapse" data-bs-target=".header-nav-main nav">
									<i class="fas fa-bars"></i>
								</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>
    <div class="container-fluid">
        <main role="main" class="main">
            @RenderBody()
        </main>
    </div>

    <footer id="footer" class="m-0 p-0">
				<div class="footer-copyright bg-color-light m-0">
					<div class="container">
						<div class="row">
							<div class="col-lg-12 m-0">
								<p class="custom-text-color-2">© Copyright 2022. All Rights Reserved.</p>
							</div>
						</div>
					</div>
				</div>
	</footer>
	</div>






    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
	<!-- Vendor -->
	<script src="~/vendor/plugins/js/plugins.min.js"></script>

	<!-- Theme Base, Components and Settings -->
	<script src="~/js/theme.js"></script>

	<!-- Current Page Vendor and Views -->
	<script src="~/js/views/view.contact.js"></script>

	<!-- Demo -->
	<script src="~/js/demos/demo-resume.js"></script>

	<!-- Theme Custom -->
	<script src="~/js/custom.js"></script>

	<!-- Theme Initialization Files -->
	<script src="~/js/theme.init.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>